# Generated by Django 5.1.1 on 2024-09-09 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    'category',
                    models.CharField(
                        choices=[
                            ('Groceries', 'Groceries'),
                            ('Leisure', 'Leisure'),
                            ('Electronics', 'Electronics'),
                            ('Utilities', 'Utilities'),
                            ('Clothing', 'Clothing'),
                            ('Health', 'Health'),
                            ('Others', 'Others'),
                        ],
                        max_length=100,
                    ),
                ),
                ('description', models.TextField()),
                ('time', models.DateTimeField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
